# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "Arch-Controller" do |arch|
    arch.vm.box = "terrywang/archlinux"
    arch.vm.hostname = "Arch-Controller"
    arch.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "Arch-Controller"
      vb.cpus = 1
      vb.memory = 1024
    end
    
    arch.vm.synced_folder "./configs", "/home/vagrant"
    arch.vm.synced_folder "./cloud-provisioner", "/home/vagrant"
    arch.vm.provision "shell", path: "scripts/setup-arch.sh"
  end
end
