# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"

  config.vm.provision "shell", inline: <<-SHELL
    ##########################
    ###SYSTEM_CONFIGURATION###
    ##########################
    timedatectl set-timezone Australia/Adelaide  # Set timezone to Adelaide
    echo "rapture-controller" > /etc/hostname  # Change the hostname
    systemctl enable systemd-timesyncd  # Enable timesync daemon on boot
    echo "vagrant:changeme" | chpasswd  # Change vagrants password to changeme
    userdel terry  # Delete user terry
    git clone https://github.com/mi-pacman/rapture-controller  # Fetch Rapture modules
    chown -R vagrant:vagrant /home/vagrant/rapture-controller  # Set permissions on repo
    cp /home/vagrant/rapture-controller/.bashrc /home/vagrant/.bashrc  # Copy over bash profile

    ##########################
    ###DOCKER_CONFIGURATION###
    ##########################
    pacman -Sy  # Update repos
    pacman -S --noconfirm docker docker-compose  # Update repositories, install docker and compose
    systemctl enable docker && systemctl start docker  # Enable and start docker daemon on boot
    docker pull midockerdb/rapture:terraform-controller  # Pull custom terraform container image
    docker pull midockerdb/rapture:packer-controller  # Pull custom packer container image

    reboot
  SHELL
end
