# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "terrywang/archlinux"

  config.vm.provision "shell", inline: <<-SHELL
     pacman --verbose -Sy && pacman --verbose --noconfirm -S docker docker-compose
     systemctl enable docker
  SHELL
end
