# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  #config.vm.provider "virtualbox" do |vb|
    #vb.memory = "1024"  # Customize the amount of memory on the VM:
  #end
  config.vm.provision "shell", inline: <<-SHELL
    timedatectl set-timezone Australia/Adelaide  # Set timezone to Adelaide
    echo "docker-controller" > /etc/hostname  # Change the hostname
    pacman -Sy && pacman -S --noconfirm docker docker-compose  # Update repositories, install docker and compose
    systemctl enable systemd-timesyncd  # Enable timesync daemon on boot
    systemctl enable docker  # Enable docker daemon on boot
    groupadd pacman  # Create pacman group
    useradd -m -g pacman -G wheel -s /bin/bash pacman  # Create user pacman
    echo "pacman:changeme" | chpasswd  # Change pacmans password to changeme
    echo "vagrant:changeme" | chpasswd  # Change vagrants password to changeme
    echo "pacman ALL=(ALL:ALL) ALL" > /etc/sudoers.d/pacman  # Add pacman to sudoers
    cp .bashrc .tmux.conf .viminfo .vimrc /home/pacman  # Copy program configs to pacmans home dir
    rm /etc/sudoers.d/vagrant  # Remove user vagrant from sudoers
    userdel terry  # Delete user terry
    reboot
  SHELL
end
